# Project information
site_name: Harvester - Open Source Hyperconverged Infrastructure
site_url: https://docs.harvesterhci.io

# Repository
repo_name: harvester/harvester
repo_url: https://github.com/harvester/harvester
edit_uri: https://github.com/harvester/docs/edit/main/docs/
# Set to false for local docs development
strict: true

theme:
  name: material
  logo: 'assets/logo_horizontal_white.png'
  favicon: 'assets/favicon.ico'
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/eye-outline
        name: Dark Mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/eye
        name: Light Mode
  icon:
    repo: fontawesome/brands/github

# Customization
extra:
  version:
    provider: mike
  homepage: https://harvesterhci.io

extra_css:
  - stylesheets/extra.css
  - ../../assets/swagger-ui/swagger-ui.css

extra_javascript:
  - ../../assets/swagger-ui/swagger-ui-bundle.js

#google_analytics:
plugins:
  - search
  - render_swagger
  #- markdownextradata: {}

markdown_extensions:
- codehilite
- admonition
- pymdownx.tabbed
- pymdownx.superfences
- attr_list
- toc:
    permalink: true

nav:
  - index.md
  - Installation:
    - install/iso-install.md
    - install/usb-install.md
    - install/pxe-boot-install.md
    - install/harvester-configuration.md
    - install/management-address.md
  - airgap.md
  - Upgrade:
    - upgrade/automatic.md
    - upgrade/v1-0-1-to-v1-0-2.md
    - upgrade/v1-0-0-to-v1-0-1.md
  - authentication.md
  - upload-image.md
  - host/host.md
  - VM Management:
    - vm/create-vm.md
    - vm/create-windows-vm.md
    - vm/edit-vm.md
    - vm/access-to-the-vm.md
    - vm/backup-restore.md
    - vm/live-migration.md
    - vm/hotplug-volume.md
    - vm/resource-overcommit.md
  - Networking:
    - networking/harvester-network.md
    - Best Practice:
      - networking/best-practice/overview.md
      - networking/best-practice/multiple-nics-vlan-aware-switch.md
      - networking/best-practice/multiple-nics-non-vlan-aware-switch.md
      - networking/best-practice/single-nic-vlan-aware-switch.md
      - networking/best-practice/single-nic-non-vlan-aware-switch.md
  - monitoring/monitoring.md
  - Rancher Integration:
    - rancher/rancher-integration.md
    - rancher/virtualization-management.md
    - Harvester Node Driver:
      - rancher/node-driver.md
      - rancher/rke1-cluster.md
      - rancher/rke2-cluster.md
      - rancher/k3s-cluster.md
    - rancher/cloud-provider.md
    - rancher/csi-driver.md
  - terraform/terraform.md
  - settings/settings.md
  - dev/dev-mode.md
  - Troubleshooting:
    - troubleshooting/installation.md
    - troubleshooting/harvester.md
    - troubleshooting/os.md
    - troubleshooting/monitoring.md
  - Reference:
    - reference/api.md
  - faq.md
