# Project information
site_name: Harvester - Open Source Hyperconverged Infrastructure
site_url: https://docs.harvesterhci.io

# Repository
repo_name: harvester/harvester
repo_url: https://github.com/harvester/harvester
edit_uri: https://github.com/harvester/docs/edit/main/docs/
# Set to false for local docs development
strict: true

theme:
  name: material
  logo: 'assets/logo_horizontal_white.png'
  favicon: 'assets/favicon.ico'
  palette:
    primary: green
  icon:
    repo: fontawesome/brands/github

# Customization
extra:
  version:
    provider: mike
  homepage: https://harvesterhci.io

extra_css:
  - stylesheets/extra.css
  - ../../assets/swagger-ui/swagger-ui.css

extra_javascript:
  - ../../assets/swagger-ui/swagger-ui-bundle.js

#google_analytics:
plugins:
  - search
  - render_swagger
  #- markdownextradata: {}

markdown_extensions:
- codehilite
- admonition
- pymdownx.tabbed
- pymdownx.superfences
- toc:
    permalink: true

nav:
  - index.md
  - Installation:
    - install/iso-install.md
    - install/pxe-boot-install.md
    - install/harvester-configuration.md
    - install/terraform.md
  - authentication.md
  - upgrade.md
  - harvester-network.md
  - import-image.md
  - VM Management:
    - vm/create-vm.md
    - vm/access-to-the-vm.md
    - vm/backup-restore.md
    - vm/live-migration.md
  - Rancher Integration:
    - rancher/rancher-integration.md
    - rancher/node-driver.md
  - Development:
    - dev/dev-mode.md
  - Reference:
    - reference/api.md
